_welcome:
    path:     /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

_import:
    path:     /import
    defaults: { _controller: AcmeDemoBundle:Welcome:import }

_notes:
    path:     /notes
    defaults: { _controller: AcmeDemoBundle:Welcome:notes }
